apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-worker
  namespace: voting-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-worker
  template:
    metadata:
      labels:
        app: voting-worker
    spec:
      containers:
      - name: voting-worker
        image: dockersamples/examplevotingapp_worker
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
