apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-ingress
  namespace: voting-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: voting.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voting-app
            port:
              number: 80
  - host: result.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 80

    